#!/bin/bash
##RONMENT SETTINGS; CHANGE WITH CAUTION
#SBATCH --export=NONE                #Do not propagate environment
#SBATCH --get-user-env=L             #Replicate login environment

##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=terra-tune-job
#SBATCH --time=20:00:00              
#SBATCH --ntasks=28      
#SBATCH --mem=40G                  
#SBATCH --output=tune-output
#SBATCH --gres=gpu:1                #Request 1 GPU per node can be 1 or 2
#SBATCH --partition=gpu              #Request the GPU partition/queue

##OPTIONAL JOB SPECIFICATIONS


#SBATCH --account=122751303855
#SBATCH --mail-type=ALL              #Send email on all job event
#SBATCH --mail-user=zhoufangtong@tamu.edu    #Send all emails to email_address 

module load Anaconda/3-5.0.0.1
module load cuDNN/6.0-CUDA-8.0.44
source activate zft
python step-one-tune.py
